#
# Configuration
#

sudo: required
dist: trusty

notifications:
  email: true

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - 6

branches:
  only:
    - master

#
# Build Lifecycle:
#

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm run test-ci
  - npm run e2e

after_success:
  # Send coverage info off to cloud ppl
  - ./node_modules/.bin/codecov
